"""Added date_time to user table

Revision ID: 939e81c1fb46
Revises: 3a5a51a1c687
Create Date: 2024-07-08 01:30:30.198153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939e81c1fb46'
down_revision: Union[str, None] = '3a5a51a1c687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_users_date_created'), 'users', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_date_created'), table_name='users')
    op.drop_column('users', 'date_created')
    # ### end Alembic commands ###
