"""removed date_time created

Revision ID: db7ea1584513
Revises: 939e81c1fb46
Create Date: 2024-07-08 01:36:35.566576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db7ea1584513'
down_revision: Union[str, None] = '939e81c1fb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_date_created', table_name='users')
    op.drop_column('users', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index('ix_users_date_created', 'users', ['date_created'], unique=False)
    # ### end Alembic commands ###
